services:
  - type: web
    name: thousand-hills-schedule-creator
    runtime: python
    buildCommand: pip install -r requirements-web.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
